# Generated by Django 6.0.1 on 2026-01-22 09:50

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ChaiType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("image", models.ImageField(blank=True, null=True, upload_to="chais/")),
                (
                    "chai_type",
                    models.CharField(
                        choices=[
                            ("ML", "Masala Chai"),
                            ("EL", "Elaichi Chai"),
                            ("GR", "Ginger Chai"),
                        ],
                        max_length=2,
                    ),
                ),
                ("price", models.TextField()),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
