# Generated by Django 6.0.1 on 2026-01-21 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="chaitype",
            name="price",
            field=models.IntegerField(default=""),
        ),
    ]
