# Generated by Django 6.0.1 on 2026-01-21 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0002_chaitype_price"),
    ]

    operations = [
        migrations.AlterField(
            model_name="chaitype",
            name="price",
            field=models.IntegerField(default=0),
        ),
    ]
