# Generated by Django 6.0.1 on 2026-01-21 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0003_alter_chaitype_price"),
    ]

    operations = [
        migrations.AlterField(
            model_name="chaitype",
            name="price",
            field=models.TextField(default=""),
        ),
    ]
